### PR TITLE
feat: Add optional setup environment notebook for

### PR DESCRIPTION
**Pull request by siliang-j-1225**
Add optional setup environment notebook for simplified Azure resource setup

# Type of PR
- Documentation changes
- Code changes

## Purpose
Add a SETUP_ENVIRONMENT.ipynb notebook to assist setting up environment.

## Does this introduce a breaking change? If yes, details on what can break
No.

## Author pre-publish checklist

- [ ] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [x] Made corresponding changes to the documentation

## Validation steps
Follow instructions in the notebook to create environment.

## Issues Closed or Referenced
No.

### CODE REVIEW

**Review by thurstonchen — COMMENTED** [review]
Hi @siliang-j-1225,
Thanks for the PR!
Just two cents:
- Maybe we change the notebook name to _deploy.ipynb_ or _deploy_azure_resources.ipynb_? Checked the naming convention for the IAC scripts of other samples in the MDW repo, they normally call deploy.sh
- Notice there're instructions in the first cell on how to run this notebook, how about we also mention that README as well, so that audiences could know it before opening the notebook? Thanks! :- )

**Comment by siliang-j-1225** [comment]
> Hi @siliang-j-1225, Thanks for the PR! Just two cents:
> 
> * Maybe we change the notebook name to _deploy.ipynb_ or _deploy_azure_resources.ipynb_? Just checked the naming convention for the IAC scripts of other samples in the MDW repo, and notice they normally call deploy.sh
> * Notice there're instructions in the first cell on how to run this notebook, how about we also mention that in README as well, so that audiences could know it before opening the notebook? Thanks! :- )

Thanks for the comment. Good points! I renamed SETUP_ENVIRONMENT.ipynb to deploy.ipynb, and updated related docs

**Comment by thurstonchen** [comment]
> Thanks for the comment. Good points! I renamed SETUP_ENVIRONMENT.ipynb to deploy.ipynb, and updated related docs

Hi Siliang, 
Thanks for the quick updates!
BTW, just added Anuj as reviewer to have the final check, thanks @promisinganuj ! :- )

**Comment by siliang-j-1225** [comment]
as the branch feat/single-tech/feature_engineering_on_fabric is already merged(by PR https://github.com/Azure-Samples/modern-data-warehouse-dataops/pull/652), created new PR https://github.com/Azure-Samples/modern-data-warehouse-dataops/pull/654 here to merge the changes to main branch.

**Pull request closed without merging**
