### PR TITLE
123 fix naming

### PR DESCRIPTION
**Pull request by akirakakar**
## Purpose

* Fixed lints errors for docs
* Changed name for eventhubs
* Add subscription id in keyvault

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Author pre-publish checklist:

- [x] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [x] Made corresponding changes to the documentation

### CODE REVIEW

**Comment by jmostella** [comment]
@akirakakar Why did we need to rename these?

**Comment by akirakakar** [comment]
> @akirakakar Why did we need to rename these?
It was confusing which one we are ingesting to.

**Comment by DavidBurela** [comment]
The eventhub names were a little confusing, and we had made mistakes between us around which were the ingest.

It now flows as:
Sensors => `evh-ingest` => `evh-FilteredDevices` =>   `evh-analytics` || `evh-outofbounds`

**Comment by jmostella** [comment]
@DavidBurela @akirakakar No opposition to renaming. But I felt that it would be better to name them __entities__ contained in them vs based on whether they are intended to be used for a _specific_ function's __output__ or __input__

**Comment by DavidBurela** [comment]
@akirakakar FYI Shervyna's completed PR has caused a merge conflict now with yours.

**Comment by DavidBurela** [comment]
@akirakakar  Setting as draft while you make a few changes based on our call.
Change it back to "ready for review" once your final commits are in and I'll pull it in.

**Comment by akirakakar** [comment]
Screen Shot 2021-02-14 at 21 25 42
Screen Shot 2021-02-14 at 21 25 19

Confirm update is working with new naming.

**Review by DavidBurela — APPROVED** [review]

**Pull request merged**
