### PR TITLE
Single tech/databricks 160 sample documentation

### PR DESCRIPTION
**Pull request by namitms**
## Purpose
* Read me for Sample 1

## Does this introduce a breaking change?
- [ ] Yes
- [x] No

## Author pre-publish checklist:
- [ ] Added test to prove my fix is effective or new feature works
- [ ] No PII in logs
- [x] Made corresponding changes to the documentation

### CODE REVIEW

**Comment by devlace** [comment]
Looks good so far., thanks Namit :) Just a few things from me on the organization of the content. 

1. Can we move Architecture and Technologies used as a subsection under Solution Overview.
2. Move WAF concepts before "How to use this sample" -- just so WAF doesn't get buried under all the screenshots.
3. Add a link to "How to use this sample" at end of Solution Overview section before 1.1 Scope so users can jump straight there if that is what they are after.

On the architecture diagram, we can take out the line to Github as the fact that its hosted in Github is inconsequential to the sample.

**Review by devlace — CHANGES_REQUESTED** [review]
Looks good so far., thanks Namit :) Just a few things from me on the organization of the content.

Can we move Architecture and Technologies used as a subsection under Solution Overview.
Move WAF concepts before "How to use this sample" -- just so WAF doesn't get buried under all the screenshots.
Add a link to "How to use this sample" at end of Solution Overview section before 1.1 Scope so users can jump straight there if that is what they are after.
On the architecture diagram, we can take out the line to Github as the fact that its hosted in Github is inconsequential to the sample.

**Comment by namitms** [comment]
> Looks good so far., thanks Namit :) Just a few things from me on the organization of the content.
> 
> 1. Can we move Architecture and Technologies used as a subsection under Solution Overview.
> 2. Move WAF concepts before "How to use this sample" -- just so WAF doesn't get buried under all the screenshots.
> 3. Add a link to "How to use this sample" at end of Solution Overview section before 1.1 Scope so users can jump straight there if that is what they are after.
> 
> On the architecture diagram, we can take out the line to Github as the fact that its hosted in Github is inconsequential to the sample.

@devlace , Thanks for the review. I have incorporated the changes suggested by you. Please review.

**Comment by Azadehkhojandi** [comment]
Hi @namitms . 
based on @devlace below feedback,

> Add a link to "How to use this sample" at end of Solution Overview section before 1.1 Scope so users can jump straight there if that is what they are after.

You added "Details about [how to use this sample](#3-how-to-use-this-sample) can be found in the later sections of this document." in the scope section not before scope section.

**Review by Azadehkhojandi — APPROVED** [review]
looks good to me, thanks. Nice diagram!

**Comment by devlace** [comment]
@namitms The readme changes looks good :) 

I just noticed that you are adding a submodule to root? What is this submodule?

**Review by devlace — COMMENTED** [review]
@namitms  The readme changes looks good. I just noticed you are adding a submodule to the root. What is this submodule?

**Comment by namitms** [comment]
> @namitms The readme changes looks good. I just noticed you are adding a submodule to the root. What is this submodule?

Good catch. it was accidental :). Removed it

**Comment by devlace** [comment]
LGTM 👍

**Pull request merged**
