### PR TITLE
update for task #685

### LINKED ISSUE #685: AZ Logins attached to multiple Tenants tries to authenticate to all.
Consider adding AD Tenant to environment vars and doing `az login --tenant TENANT_ID` to explicitly login to a tenant.

DOD
- Make the login/tenant selection consistent with other MDE Samples
- Documentation update or script update to explicitly select tenant for sample deployment.

### PR DESCRIPTION
**Pull request by thesqlpro**
# Type of PR

- Documentation changes
Rework from the reverted PR (#907) to address AZ Login in just the e2e Repo for Databricks

## Author pre-publish checklist

- [X ] Added test to prove my fix is effective or new feature works
- [X] No PII in logs
- [X] Made corresponding changes to the documentation

## Validation steps

- ...

## Issues Closed or Referenced

- Closes #685 

- References #issue_number

### CODE REVIEW

**Review by bsherwin — APPROVED** [review]
Looks good.

**Review by elenaterenzi — APPROVED** [review]
LGTM

**Comment by thesqlpro** [comment]
Merged, done.

**Comment by thesqlpro** [comment]
Deleting branch

**Pull request merged**
