### PR TITLE
add ACL in datalake for adf managed identity

### PR DESCRIPTION
**Pull request by shervyna**
## Purpose
Add ACL(access control list) for ADF managed identity in order to access datalake

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Author pre-publish checklist:

- [ ] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [ ] Made corresponding changes to the documentation

### CODE REVIEW

**Review by jmostella — APPROVED** [review]

**Review by akirakakar — APPROVED** [review]
lgtm

**Comment by akirakakar** [comment]
Something we did in last project was running this to create automatic wiki. In you are interested, https://github.com/terraform-docs/terraform-docs

**Review by NT-D — APPROVED** [review]
LGTM

**Comment by shervyna** [comment]
> Something we did in last project was running this to create automatic wiki. In you are interested, https://github.com/terraform-docs/terraform-docs

@akirakakar haha yeah I was thinking about it as well, but then I will need to add devcontainer to this repo as well (takes more time :D ) maybe we can do this as a stretch goal

**Pull request merged**
