### PR TITLE
831 - Isolate solution images.

### LINKED ISSUE #831: Create independent IMG folder for parking sensor sample
Across the repository each sample should have its own img folder.

**DoD**
- Move all the images into an image folder within the parking sensor databricks sample
- Make sure all links are references are correct

### PR DESCRIPTION
**Pull request by bsherwin**
# Type of PR
- Documentation changes

## Purpose
Moving images from parent folder to solution specific folder to isolate solution changes.

## Does this introduce a breaking change? If yes, details on what can break
No

## Author pre-publish checklist
[X ] Made corresponding changes to the documentation

## Validation steps
Verify all images in E2E Sample documentation reference valid files.

## Issues Closed or Referenced
- Closes #831
- References #888

### CODE REVIEW

**Comment by bsherwin** [comment]
Normally, I wouldn't create this PR direct to main, but for some reason the intermediate branch was not working on my computer, so I took a shortcut and went direct to main.

**Review by thesqlpro — APPROVED** [review]
Simple path changes, looks good!

**Review by ydaponte — CHANGES_REQUESTED** [review]
@bsherwin the link inspector is raising issues on all the links - I think you need to change either the way the path is built or change the configuration on the linkinspector.yml: https://github.com/UmbrellaDocs/linkspector?tab=readme-ov-file#directories-to-search

**Comment by bsherwin** [comment]
@ydaponte - That's interesting, because the preview works just fine. I'll have to dig into the linkspector to figure out how it is resolving the link and failing.

**Comment by bsherwin** [comment]
> @bsherwin the link inspector is raising issues on all the links - I think you need to change either the way the path is built or change the configuration on the linkinspector.yml: https://github.com/UmbrellaDocs/linkspector?tab=readme-ov-file#directories-to-search

@ydaponte...the "directories to search" is a configuration of where to look for markdown files. I think the problem was the "?raw=true" on the end of the image links. Anyway...they are all clear now. Please review and approve.

**Comment by ydaponte** [comment]
@bsherwin - you are still requesting to merge to main. Can you change to the feature branch please?

**Comment by bsherwin** [comment]
Sure...I'll just redo this.

**Pull request closed without merging**
