### PR TITLE
Single tech/databricks 195 bug destroy

### PR DESCRIPTION
**Pull request by tomomi-code**
## Purpose

*  Fix.bug: #195

**UPDATED**
I discussed with @jsburckhardt and we decided to have a validation to check if the resource exists in advance since the `az delete` command won't fail even if a resource is not found.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Author pre-publish checklist:

- [ ] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [ ] Made corresponding changes to the documentation

### CODE REVIEW

**Review by Azadehkhojandi — CHANGES_REQUESTED** [review]
After discussion, we agreed on destroy script should have two options
1- Delete the whole resource group
2- Delete the resources under the resource group, if the resource doesn't exist, move on to the next resource
change request --> current script exits when the resource is not there and doesn't delete the rest of the resources

**Comment by tomomi-code** [comment]
> After discussion, we agreed on destroy script should have two options
> 1- Delete the whole resource group
> 2- Delete the resources under the resource group, if the resource doesn't exist, move on to the next resource
> change request --> current script exits when the resource is not there and doesn't delete the rest of the resources

Thanks Az :)
I updated the PR as we discussed. If I run the `destroy.sh` against the empty resource group it keeps going until the end. (You can confirm it in the following screenshot.)
image

**Review by jsburckhardt — APPROVED** [review]
LGTM

**Review by jsburckhardt — CHANGES_REQUESTED** [review]
Hi @tomomi-code, I think we should update `destroy.sh` from sample1 as well

**Comment by tomomi-code** [comment]
@jsburckhardt Good point. After this PR merged I will raise a new PR for sample1 since this branch will merge to `single-tech/databricks_sample2` not `single-tech/databricks`.

**Review by jsburckhardt — APPROVED** [review]

**Review by Azadehkhojandi — APPROVED** [review]

**Pull request merged**
